### ISSUE TITLE
Top of tavern south wall and Chicken House barrels aren't solid

### ISSUE THREAD

**Issue by cassidoxa** [bonimy/zelda3-palette-randomizer#1]
When the palette is randomized, the barriers in these locations don't act as they normally do. It is possible to walk partially on top of the South wall of the Northern part of the tavern (where the chest is.) Link can also take unexpected spike damage in this area. The barrels (?) in the Chicken House room with the chest also display some strange behavior.

**Comment by bonimy** [comment]
Thanks for the info. One of the ROM locations I write to was incorrect and wrote on the tile behavior properties. Will push an update as soon as I verify the problem is removed.

Thanks for using the palette randomizer.

**Comment by cassidoxa** [comment]
No problem. Thanks for developing this. I really prefer it over the stock palette shuffle and have been using it a lot for multiworld lately.

**Comment by bonimy** [comment]
a7da4b32b6b75122ce3d092f0388472c5b3ff25e fixes this issue. Prerelease [v0.9.1](https://github.com/bonimy/zelda3-palette-randomizer/releases/tag/v0.9.1) is now available.
