### ISSUE TITLE
Split Overworld and Dungeon Palette Shuffles

### ISSUE THREAD

**Issue by Berserker66** [bonimy/zelda3-palette-randomizer#2]
To not have a feature regression, those two would need to be seperate options for inclusion in [https://github.com/Berserker66/MultiWorld-Utilities](https://github.com/Berserker66/MultiWorld-Utilities)

**Comment by bonimy** [comment]
Added command line args `--(no-)overworld` and `--(no-)dungeon` to toggle respective palette shuffles. @Berserker66, let me know if this solves the issue.

**Comment by bonimy** [comment]
Functionality implemented. Closing.
