### ISSUE TITLE
Greyscale is very dark

### ISSUE THREAD

**Issue by compiling** [bonimy/zelda3-palette-randomizer#3]
![image](https://user-images.githubusercontent.com/8335770/82439885-c5319680-9ade-11ea-9d96-ff63ecc86597.png)

**Comment by bonimy** [comment]
I changed up the grayscale algorithm a bit. Which looks better? Left (preserving lightness), or right (preserving luma)?

![image](https://user-images.githubusercontent.com/12055044/82488467-cb028a00-9a94-11ea-8058-ca2ecab2bc46.png)

**Comment by compiling** [comment]
I like the right side better. On the left side, the water looks too bright.

**Comment by compiling** [comment]
Actually, I think the problem is you were using a luma preserving greyscale before, then dividing by 3 (an artifact of an old greyscale doing an average?)

This is what I get without the division:
![image](https://user-images.githubusercontent.com/8335770/82509804-42472500-9b4c-11ea-9994-9ebbab179532.png)

**Comment by bonimy** [comment]
Agreed on the water. The grayscale algorithm has been added.
